function [ val ] = grad( x, a, d )
val = -4*(norm(a(:, 1) - x)^2 - d(1)^2) * (a(:, 1) - x) ...
    -4*(norm(a(:, 2) - x)^2 - d(2)^2) * (a(:, 2) - x) ...
    -4*(norm(a(:, 3) - x)^2 - d(3)^2) * (a(:, 3) - x);
end
